project_name: chatgpt_reverse_proxy


before:
  hooks:
    - go mod tidy


builds:
  - id: reverse_proxy
    binary: chatgpt_reverse_proxy
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.AppName={{.Binary}}
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.Version={{.Version}}
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.BuildCommit={{.ShortCommit}}
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.BuildTime={{.CommitDate}}
      - -extldflags
      - -static
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
      - arm
      - riscv64
    goamd64:
      - v2
    goarm:
      - 7
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
    mod_timestamp: '{{ .CommitTimestamp }}'


  - id: tencentcloud_scf
    binary: main
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.AppName=tencentcloud_scf_chatgpt_reverse_proxy
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.Version={{.Version}}
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.BuildCommit={{.ShortCommit}}
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.BuildTime={{.CommitDate}}
      - -extldflags
      - -static
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v2
    mod_timestamp: '{{ .CommitTimestamp }}'


  - id: huaweicloud_func
    binary: main
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.AppName=huaweicloud_func_chatgpt_reverse_proxy
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.Version={{.Version}}
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.BuildCommit={{.ShortCommit}}
      - -X github.com/lenye/chatgpt_reverse_proxy/pkg/version.BuildTime={{.CommitDate}}
      - -extldflags
      - -static
    flags:
      - -trimpath
      - -tags=huawei
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v2
    mod_timestamp: '{{ .CommitTimestamp }}'


archives:
  - id: reverse_proxy
    builds:
      - reverse_proxy
    name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md


  - id: tencentcloud_scf
    builds:
      - tencentcloud_scf
    name_template: 'tencentcloud_scf_chatgpt_reverse_proxy_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: zip
    files:
      - scf_bootstrap
      - LICENSE
      - README.md


  - id: aliyun_fc
    builds:
      - tencentcloud_scf
    name_template: 'aliyun_fc_chatgpt_reverse_proxy_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: zip
    files:
      - /code/bootstrap
      - LICENSE
      - README.md


  - id: huaweicloud_func
    builds:
      - huaweicloud_func
    name_template: 'huaweicloud_func_chatgpt_reverse_proxy_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: zip
    files:
      - bootstrap
      - LICENSE
      - README.md


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"


changelog:
  filters:
    exclude:
      - '^wip:'
      - '^docs:'
      - '^test:'
      - '^style:'
      - '^chore:'
      - '^ci:'


release:
  draft: true
  replace_existing_draft: true