services:


  chatgpt_reverse_proxy:
    image: ghcr.io/lenye/chatgpt_reverse_proxy:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      OXY_PORT: "9000"
      OXY_TARGET: "https://api.openai.com"
      OXY_HOP_HEADER_PREFIX: ""
